server:
  port: 8089
  tomcat:
    max-threads: 2
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_user?seUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.ytq.falut.hundred.entity
  configuration:
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



