server:
  port: 8081
  tomcat:
    max-threads: 1
spring:
  application:
    name: spring-mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_user?seUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.ytq.data.po
  configuration:
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

secretApp: aabb